### ISSUE TITLE
server crashes after file upload

### ISSUE THREAD

**Issue by elyashiv** [elyashiv/recordingSystem-yhe#2]
After a file upload the server crashes. The error in the console:
```
[2016-07-31 17:10:38.030] [DEBUG] recodingSystem - events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EIO
    at exports._errnoException (util.js:873:11)
    at WriteStream.Socket._writeGeneric (net.js:697:26)
    at WriteStream.Socket._write (net.js:716:8)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at WriteStream.Writable.write (_stream_writable.js:214:11)
    at WriteStream.Socket.write (net.js:642:40)
    at Console.log (console.js:39:16)
    at Logger.<anonymous> (..\node_modules\log4js\lib\appenders\console.js:8:5)
    at emitOne (events.js:82:20)
```
The file did make it, and the client got a positive reply.

**Comment by mordicool** [comment]
what have you entered in the subject name?
witch type of  file was it?

**Comment by elyashiv** [comment]
a .mp3 file, פיילוט in the subject. I managed to reproduce with other subjects.

**Comment by elyashiv** [comment]
Found it - stupid problem - I was trying to get UTF-8 support, and something doesn't quite work - http://stackoverflow.com/questions/17035399/why-this-error-happend-nodejs-error-write-eio

close #2
