### ISSUE TITLE
Not all the parameters make it

### ISSUE THREAD

**Issue by elyashiv** [elyashiv/recordingSystem-yhe#7]
while trying to upload a file I get the following exception:
```
undefined:1
"}


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingForm.<anonymous> (... \recordingSystem-yhe-v-2.1\root.js:31:34)
    at emitTwo (events.js:100:13)
    at IncomingForm.emit (events.js:185:7)
    at ... \recordingSystem-yhe-v-2.1\node_modules\formidable\lib\incoming_form.js:229:12
    at WriteStream.<anonymous> (... \recordingSystem-yhe-v-2.1\node_modules\formidable\lib\file.js:70:5)
    at WriteStream.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at WriteStream.emit (events.js:179:7)
    at finishMaybe (_stream_writable.js:478:14)
```

inspecting the data recieved on the server it seems that not all the data made it on the time of the parsing - the file.name field is `'"{'` while the data send is` filename="{\"subject\":\"akuo\",\"lecturer\":\"××¨××× ××¨×××\",\"path\":\"/×××¨×\",\"fileType\":\".mp3\"}"`

psiible cause - http://stackoverflow.com/questions/13212956/node-js-and-json-runtime-error

**Comment by elyashiv** [comment]
http://stackoverflow.com/questions/38737309/nodejs-partial-data-just-from-firefox#

**Comment by elyashiv** [comment]
felixge/node-formidable#389
