### ISSUE TITLE
problem with renaming

### ISSUE THREAD

**Issue by elyashiv** [elyashiv/recordingSystem-yhe#9]
```
[2016-10-05 08:39:51.869] [ERROR] recodingSystem - Error while receiving a record. Error message: ENOENT: no such file or directory, scandir 'C:\maagar\root\הקלטות\גמרא\עיון\הרמל שבת'
fs.js:53
        throw backtrace;
        ^

Error: ENOENT: no such file or directory, rename 'C:\maagar\root\הקלטות\upload_a70ab33a75b2404e171a4975cd6302c6' -> 'C:\maagar\root\הקלטות\גמרא\עיון\הרמל שבת\המשך עקירה והנחה ממקום ד על ד.mp3'
    at rethrow (fs.js:48:21)
    at makeCallback (fs.js:74:12)
    at Object.fs.rename (fs.js:668:14)
    at C:\recordingSystem-yhe\modules\filePathRedirector.js:15:16
    at _fulfilled (C:\recordingSystem-yhe\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\recordingSystem-yhe\node_modules\q\q.js:863
:30)
    at Promise.promise.promiseDispatch (C:\recordingSystem-yhe\node_modules\q\q.
js:796:13)
    at C:\recordingSystem-yhe\node_modules\q\q.js:604:44
    at runSingle (C:\recordingSystem-yhe\node_modules\q\q.js:137:13)
    at flush (C:\recordingSystem-yhe\node_modules\q\q.js:125:13)

```

**Comment by elyashiv** [comment]
Might have to do with comparstion of the following two lines:
[filePathRedirector.js L28](https://github.com/elyashiv/recordingSystem-yhe/blob/master/modules/filePathRedirector.js#L28)
[formidableBuilder.js L14](https://github.com/elyashiv/recordingSystem-yhe/blob/master/modules/formidableBuilder.js#L14)
